// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class Department
{
    public int Id { get; set; }

    public string DepartmentCode { get; set; }

    public string DepartmentName { get; set; }

    public int? ParentId { get; set; }
}