// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class OrderDetailInfo
{
    public int Id { get; set; }

    public int? OrderDetailId { get; set; }

    public int? SerialId { get; set; }

    public string ProductSerial { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}