// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class Quotation
{
    public int Id { get; set; }

    public string QuotationNumber { get; set; }

    public int? WarrantyClaimId { get; set; }

    public string CustomerName { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerPhoneNumber { get; set; }

    public string CustomerAddress { get; set; }

    public int? ProductSerialId { get; set; }

    /// <summary>
    /// 1 = Đã gửi, 2 = Chưa gửi, 3 = Đã duyệt, 4 = Đã từ chối, 5 = Hết hạn
    /// </summary>
    public int? StatusQuotation { get; set; }

    public string Note { get; set; }

    public DateTime? DeadLine { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public int? StatusReply { get; set; }

    public DateTime? ReplyDate { get; set; }

    public string ReplyNote { get; set; }

    public decimal? Vatfee { get; set; }

    public bool? IsDeleted { get; set; }
}