// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class QuotationDetail
{
    public int Id { get; set; }

    public int? QuotationId { get; set; }

    public int? SparePartId { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? Price { get; set; }

    public bool? IsDeleted { get; set; }
}