// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class ResponseHistory
{
    public int Id { get; set; }

    public int? WarrantyClaimId { get; set; }

    public DateTime? ResponseDate { get; set; }

    public int? CustomerId { get; set; }

    public string ResponseText { get; set; }

    public int? ReceptionWorkerId { get; set; }

    /// <summary>
    /// 1 = Chờ xử lý, 2 = Đang xử lý, 3 = Đã giải quyết, 4 = Đã đóng
    /// </summary>
    public int? Status { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}