// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class SparePart
{
    public int Id { get; set; }

    public int? SparePartGroupId { get; set; }

    public int? ProductId { get; set; }

    public int? UnitId { get; set; }

    public string SparePartNumber { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }
}