// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class UserGroupLink
{
    public int Id { get; set; }

    public int? UserGroupId { get; set; }

    public int? UserId { get; set; }
}