// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class User
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string LoginName { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public DateOnly? BirthOfDate { get; set; }

    public int? Sex { get; set; }

    public string Qualifications { get; set; }

    public string BankAccount { get; set; }

    public string Bhyt { get; set; }

    public string Mst { get; set; }

    public string Bhxh { get; set; }

    public string Cmtnd { get; set; }

    public string JobDescription { get; set; }

    public string Telephone { get; set; }

    public string HandPhone { get; set; }

    public string HomeAddress { get; set; }

    public string Resident { get; set; }

    public string PostalCode { get; set; }

    public int? DepartmentId { get; set; }

    public int? Status { get; set; }

    public string Communication { get; set; }

    public DateOnly? PassExpireDate { get; set; }

    public sbyte? IsCashier { get; set; }

    public int? CashierNo { get; set; }

    public string EmailCom { get; set; }

    public string Email { get; set; }

    public DateOnly? StartWorking { get; set; }

    public int? UserGroupId { get; set; }

    public int? UserGroupSxid { get; set; }

    public int? MainViewId { get; set; }

    public string Position { get; set; }

    public sbyte? IsSetupFunction { get; set; }

    public string ImagePath { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public sbyte? IsAdmin { get; set; }

    public sbyte? StaffAltax { get; set; }

    public sbyte? StaffHyp { get; set; }

    public sbyte? StaffKnife { get; set; }

    public string ApprovedBy { get; set; }
}