// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class UserGroupRightDistribution
{
    public int Id { get; set; }

    public int FormAndFunctionId { get; set; }

    public int UserGroupId { get; set; }
}