// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class UserGroup
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public int? Leader { get; set; }

    public int? DepartmentId { get; set; }
}