// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class WarrantyClaimTracking
{
    public int Id { get; set; }

    public int WarrantyClaimId { get; set; }

    public string StatusText { get; set; }

    public string Note { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }
}