// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class WarrantyClaimUsedSparePart
{
    public int Id { get; set; }

    public int? WarrantyClaimId { get; set; }

    public int? SparePartId { get; set; }

    public int? UnitId { get; set; }

    public decimal? Quantity { get; set; }

    public string Note { get; set; }

    public bool? IsDeleted { get; set; }
}