// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class WarrantyClaim
{
    public int Id { get; set; }

    public string ClaimNo { get; set; }

    public string CustomerName { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerPhoneNumber { get; set; }

    public string CustomerAddress { get; set; }

    public int? ProductId { get; set; }

    public int? IssueId { get; set; }

    public string SerialNumber { get; set; }

    /// <summary>
    /// Có bao silicon bảo vệ hay không?
    /// </summary>
    public bool? HasProtection { get; set; }

    /// <summary>
    /// Có bộ đổi nguồn (Adapter) không?
    /// </summary>
    public bool? HasAdapter { get; set; }

    /// <summary>
    /// Có cáp dữ liệu không
    /// </summary>
    public bool? HasCable { get; set; }

    /// <summary>
    /// Có pin không?
    /// </summary>
    public bool? HasBattery { get; set; }

    /// <summary>
    /// Có lỗi khi mở hộp không?
    /// </summary>
    public bool? HasIssueWhenOpenBox { get; set; }

    /// <summary>
    /// Có bị rơi hoặc ép, va đập không?
    /// </summary>
    public bool? HasCollision { get; set; }

    /// <summary>
    /// Môi trường sử dụng: 1 = bình thường, 2 = nóng, 3 = lạnh
    /// </summary>
    public int? OperationEnvironment { get; set; }

    public int? Status { get; set; }

    /// <summary>
    /// 1 = không có phí, 2 = có phí
    /// </summary>
    public int? Type { get; set; }

    public string FileAddress { get; set; }

    /// <summary>
    /// Công ty vận chuyển
    /// </summary>
    public string Transporter { get; set; }

    /// <summary>
    /// Số vận đơn
    /// </summary>
    public string LadingNumber { get; set; }

    public string Note { get; set; }

    /// <summary>
    /// Địa chỉ gửi máy để sửa chữa
    /// </summary>
    public string RecipientAddress { get; set; }

    public int? CustomerRating { get; set; }

    public bool? IsFinished { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool? IsDeleted { get; set; }
}