// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class WorkOrderSparePart
{
    public int Id { get; set; }

    public int? SparePartGroupId { get; set; }

    public int? WorkOrderId { get; set; }

    public bool IsDeleted { get; set; }

    public string Quantity { get; set; }
}