// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarrantySystem.Model.Entities;

public partial class WorkOrder
{
    public int Id { get; set; }

    public string Code { get; set; }

    public int? WarrantyClaimsId { get; set; }

    public int? QuotationId { get; set; }

    public int? ProductId { get; set; }

    public DateTime? DateStart { get; set; }

    public DateTime? DateEnd { get; set; }

    public int? UsersId { get; set; }

    public int? StatusId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public string Note { get; set; }

    public int? ProgressComplete { get; set; }

    public DateTime? CompletedDate { get; set; }

    public string Description { get; set; }
}